package com.mobile.tuesplace.ui.navigation

const val LOGIN_SCREEN = "login"
const val WELCOME_SCREEN = "welcome"
const val FORGOTTEN_PASSWORD_SCREEN = "forgotten_password"
const val MESSAGES_SCREEN = "messages"
const val CLASSES_SCREEN = "classes"
const val VIDEOROOM_SCREEN = "videoroom"
const val WELCOME_ADMIN_SCREEN = "welcome_admin_screen"
const val CREATE_GROUP_SCREEN = "create_group_screen"
const val ALL_GROUPS_SCREEN = "all_groups_screen"
const val EDIT_GROUP_SCREEN = "edit_group_screen/{groupId}"
const val PROFILE_SCREEN = "profile_screen"
const val EDIT_PROFILE_SCREEN = "edit_profile_screen"
const val SETTINGS_SCREEN = "settings_screen"