package com.mobile.tuesplace.ui.navigation

const val LOGIN_SCREEN = "login"
const val WELCOME_SCREEN = "welcome"
const val FORGOTTEN_PASSWORD_SCREEN = "forgotten_password"
const val CHATS_SCREEN = "chats"
const val CHATROOM_SCREEN = "chatroom"
const val CLASSES_SCREEN = "classes"
const val VIDEOROOM_SCREEN = "videoroom"
const val WELCOME_ADMIN_SCREEN = "welcome_admin_screen"
const val CREATE_GROUP_SCREEN = "create_group_screen"
const val ALL_GROUPS_SCREEN = "all_groups_screen"
const val EDIT_GROUP_SCREEN = "edit_group_screen/{groupId}"
const val PROFILE_SCREEN = "profile_screen"
const val EDIT_PROFILE_SCREEN = "edit_profile_screen"
const val SETTINGS_SCREEN = "settings_screen"
const val CLASSROOM_USER_SCREEN = "classroom_user_screen"
const val CREATE_POST = "create_post"
const val ALL_STUDENTS_SCREEN = "all_students"
const val ALL_TEACHERS_SCREEN = "all_teachers"
const val AGENDA_SCREEN = "agenda_screen"
const val ACTIVITIES_OPTION_MENU_SCREEN = "activities_option_menu_screen"
const val ACTIVITIES_STUDENTS_CLASS_MENU = "activities_students_class_menu"
const val ACTIVITIES_STUDENTS_SCREEN = "activities_students_screen"
const val ACTIVITIES_TEACHERS_SCREEN = "activities_teachers_screen"
const val ACTIVITIES_TEACHER_SCREEN = "activities_teacher_screen"
const val MY_ACTIVITIES = "my_activities_screen"
const val CURRENT_ACTIVITIES = "current_activities_screen"